# Generated by Django 6.0.5 on 2026-05-17 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(default='CLIENTE', max_length=50)),
                ('pontos', models.IntegerField(default=0)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('CLIENTE', 'Cliente Regular'), ('PINTOR', 'Pintor / Indicante')], max_length=20, unique=True)),
                ('pontos_por_real', models.IntegerField(default=1)),
                ('pontos_necessarios_resgate', models.IntegerField(default=30)),
                ('valor_resgate_reais', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('perfil', models.CharField(default='Colaborador', max_length=50)),
                ('comissao', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('indicante', models.CharField(blank=True, max_length=255, null=True)),
                ('cupom_texto', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VENDA', 'Venda Finalizada'), ('ORCAMENTO', 'Orçamento')], default='VENDA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cod_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('unidade', models.CharField(default='UN', max_length=10)),
                ('status', models.CharField(default='ATIVO', max_length=20)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.familia')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca')),
            ],
        ),
    ]
